# -*- coding: utf-8 -*-
"""web scraping .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177aUnf_La9fH3E6gNEHHq6O6eGcUZCKb
"""

!pip install requests
!pip install beautifulsoup4
!pip install pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://books.toscrape.com/"

response = requests.get(url)

print(response.status_code)

soup = BeautifulSoup(response.text, 'html.parser')

books = soup.find_all('article', class_='product_pod')

print(len(books))

titles = []
prices = []
ratings = []

for book in books:

    title = book.h3.a['title']

    price = book.find('p', class_='price_color').text

    rating = book.find('p')['class'][1]

    titles.append(title)
    prices.append(price)
    ratings.append(rating)

data = pd.DataFrame({
    'Title': titles,
    'Price': prices,
    'Rating': ratings
})

print(data.head())

data.to_csv("books_dataset.csv", index=False)

print("Dataset Saved Successfully!")

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://books.toscrape.com/"

response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

books = soup.find_all('article', class_='product_pod')

titles = []
prices = []
ratings = []

for book in books:

    title = book.h3.a['title']

    price = book.find('p', class_='price_color').text

    rating = book.find('p')['class'][1]

    titles.append(title)
    prices.append(price)
    ratings.append(rating)

data = pd.DataFrame({
    'Title': titles,
    'Price': prices,
    'Rating': ratings
})

print(data)

data.to_csv("books_dataset.csv", index=False)

print("Dataset Saved Successfully!")